<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BlockGameEngine.Runtime\BlockGameEngine.Runtime.csproj" />
    <ProjectReference Include="..\BlockGameEngine.ProjectIO\BlockGameEngine.ProjectIO.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
